plugins {
    id("java")
    id 'com.gradleup.shadow' version '9.6.1'
}

group = "com.emeraldingot.storagesystem"
version = "3.0.1"

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.9.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    compileOnly("org.spigotmc:spigot-api:26.3-R0.1-SNAPSHOT")
    implementation 'org.xerial:sqlite-jdbc:3.53.2.0'
}

tasks.named('shadowJar') {
    dependencies {
        exclude(dependency("org.xerial:sqlite-jdbc:3.53.2.0"))
    }
    exclude 'META-INF/maven/**'
}

tasks.test {
    useJUnitPlatform()
}