plugins {
    id("java")
    id 'com.gradleup.shadow' version '9.6.1'
}

group = "com.emeraldingot.storagesystem"
version = "3.0.0"

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.9.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    compileOnly("org.spigotmc:spigot-api:26.2-R0.1-SNAPSHOT")
//    compileOnly(files("../server/Spigot/Spigot-Server/target/spigot-1.21.5-R0.1-SNAPSHOT.jar"))
//    compileOnly(files("../server/plugins/ProtocolLib.jar"))
//    compileOnly 'org.spigotmc:spigot:1.21.4-R0.1-SNAPSHOT:remapped-mojang'
    implementation 'org.xerial:sqlite-jdbc:3.53.2.0'
//    implementation group: 'de.rapha149.signgui', name: 'signgui', version: '2.5.3'
}

tasks.named('shadowJar') {
    dependencies {
        exclude(dependency("org.xerial:sqlite-jdbc:3.53.2.0"))
    }
    exclude 'META-INF/maven/**'
}

tasks.test {
    useJUnitPlatform()
}